image:
  file: .gitpod.Dockerfile

tasks:
  - name: Readme
    init: gp open README.md
    command: exit

  - name: MySQL
    init: /etc/mysql/mysql-bashrc-launch.sh
    command: exit

  - name: Seed
    init: |
      gp ports await 3000
      npm run seed
    command: exit

  - name: App
    init: |
      npx -y yarn install
      gp ports await 3306
      mysql -u root -e "CREATE USER 'conduit'@'localhost' IDENTIFIED WITH mysql_native_password BY 'conduit'"
      mysql -u root -e "CREATE DATABASE conduit"
      mysql -u root -e "GRANT ALL PRIVILEGES ON conduit.* TO 'conduit'@'localhost'"
    command: npm start
    env:
      NX_DAEMON: false

ports:
  - port: 4200
    visibility: public
    onOpen: notify
  - port: 3306
    visibility: public
    onOpen: ignore
  - port: 3000
    visibility: public
    onOpen: ignore
  - port: 9229
    onOpen: ignore
  - port: 8828
    onOpen: ignore

vscode:
  extensions:
    - cweijan.vscode-mysql-client2@4.3.0
    - esbenp.prettier-vscode
    - dbaeumer.vscode-eslint
    - caponetto.vscode-diff-viewer
    - eamodio.gitlens
